FUNKTOR_APP_NAME: funktor-full-rails-deploy
FUNKTOR_INCOMING_JOB_QUEUE:
  Ref: IncomingJobQueue
FUNKTOR_DEFAULT_QUEUE:
  Ref: DefaultQueue
FUNKTOR_SINGLE_THREAD_QUEUE:
  Ref: SingleThreadQueue
BUNDLE_WITHOUT: development:test
RAILS_ENV: production
RACK_ENV: production
RAILS_LOG_TO_STDOUT: true
